"""add user roles

Revision ID: 494ca317f70d
Revises: f8488b62525e
Create Date: 2025-12-06 17:39:27.004910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494ca317f70d'
down_revision = 'f8488b62525e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
