"""profile fields

Revision ID: af4ec7fb076c
Revises: 69e844679714
Create Date: 2025-12-06 16:42:25.483615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4ec7fb076c'
down_revision = '69e844679714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('avatar_file', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('job_title')
        batch_op.drop_column('avatar_file')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
