"""add mascotes system

Revision ID: c89aa72b0005
Revises: 8c2f9a1add
Create Date: 2025-12-14 19:06:13.354516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89aa72b0005'
down_revision = '8c2f9a1add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('evolucao', sa.Integer(), nullable=True),
    sa.Column('xp_necessario', sa.Integer(), nullable=True),
    sa.Column('imagem', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascote_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mascote_id', sa.Integer(), nullable=True),
    sa.Column('evolucao_atual', sa.Integer(), nullable=True),
    sa.Column('data_adocao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mascote_id'], ['mascote.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('daily_likes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('daily_comments',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('daily_comments',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('daily_likes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    op.drop_table('mascote_usuario')
    op.drop_table('mascote')
    # ### end Alembic commands ###
